### ISSUE TITLE
Status API returns unknown error

### ISSUE THREAD

**Issue by l-hendriks** [kinecosystem/kin-ios#7]
I'm switching from the old to the new SDK and am encountering an issue.

I'm calling this:

```
        print(self.account!)
        print(self.account!.publicAddress)
        // If not registered on the blockchain, do that
        self.account!.status { (status: AccountStatus?, error: Error?) in
            print(status)
            print(error)
```

Which prints this:

```
KinSDK.KinAccount
GDYBEP2VI5FR3Y2HQ2WEJFPZE33LACIUJFTBUB3UQCMU7LJA3MDMSKMN
nil
Optional(KinBase.KinService.Errors.unknown)
```

My flow is like this:

1. Create or get local wallet if exists
2. Check if wallet exists on the blockchain
3. If no, create on the blockchain
4. Do other stuff

For step 3, I call the function above. On the old SDK this gives me either `created` or `not_created` as status, while in the new SDK the status is `nil` and I get an unknown error. Any idea what could be going on?

Thanks!

**Comment by kikengineering** [comment]
Thanks for your feedback. In your scenario, looks like the new sdk was trying to create the account on the blockchain for you when you query the status of an account that doesn't exist on-chain. This is a new behaviour that we added but looks like it's incompatible with the old sdk, because when it's being used through KinBaseCompat on the main net, there is no `KinAccountCreationApi`. 

Anyway, I'll make an update to address this issue to make sure it's backward compatible.

**Comment by kikengineering** [comment]
I just put up release 0.1.3 that should fix this issue. Let me know if it works for you.

**Comment by l-hendriks** [comment]
this is fixed now, thanks a lot!
